### ISSUE TITLE
Does this implemenation support the several MCP Servers written in Typscript? - Python Code that makes use of typescript mcp servers?

### ISSUE THREAD

**Issue by ksgnextuple** [langchain-ai/langchain-mcp-adapters#63]
Was actually trying to integrate mcp servers like
 
- https://github.com/furey/mongodb-lens
- https://github.com/QuantGeekDev/mongo-mcp

But these are written in typescript.

Can such mcp servers be converted to langchain tools and used in a python implementation?

Came across this https://github.com/hideya/langchain-mcp-tools-py, which serves my purpose but curious if there is some other way?

**Comment by eyurtsev** [comment]
It should work. It's just a communication protocol, doesn't matter what language the server is written it (e.g., server can be in Go and client can be in Fortran) as long as both client and server implement the correct protocol. Are you seeing any issues?

**Comment by ksgnextuple** [comment]
Got it, so mongodb-lens wasn't working when i used the load_mcp_tools or the MultiServerMCPClient. But when I used convert_mcp_to_langchain_tools it did work.

mongo-mcp worked though, but mongodb-lens is just stuck.

Below is the code,

```
import asyncio
import os

from langchain_mcp_adapters.client import MultiServerMCPClient
from langchain_mcp_adapters.tools import load_mcp_tools
from langgraph.prebuilt import create_react_agent
from langchain_core.messages import SystemMessage, HumanMessage
from langchain_openai import AzureChatOpenAI
from dotenv import load_dotenv
from mcp import stdio_client, StdioServerParameters, ClientSession

load_dotenv()

model = AzureChatOpenAI(
    azure_deployment="llmgpt4o",
    azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
    api_key=os.getenv("AZURE_OPENAI_API_KEY"),
    api_version="2024-08-01-preview"
)

server_params = StdioServerParameters(
    command="npx",
    args=["-y","mongo-mcp","mongodb://localhost:27017"]
)

async def run_agent():
    async with stdio_client(server_params) as (read, write):
        async with ClientSession(read, write) as session:
            # Initialize the connection
            await session.initialize()

            # Get tools
            tools = await load_mcp_tools(session)

            # Create and run the agent
            agent = create_react_agent(model, tools)
            agent_response = await agent.ainvoke({"messages": "list all collections in database config"})

            print(agent_response)

            return agent_response

# Run the agent
if __name__ == "__main__":
    response = asyncio.run(run_agent())
    print("\nFinal Response:", response)

```

**Comment by vbarda** [comment]
@ksgnextuple we pushed a new update a few days ago that should now runs typescript servers without issues - can you try again on the latest library version?

**Comment by ksgnextuple** [comment]
Still seeing the same issue, i see langchain-mcp-adapters is dependent on mcp 1.4.1 and langchain-mcp-tools (convert_mcp_to_langchain_tools) is dependent on 1.6.0. Can that cause issues?
